[build]
  command = "npm ci && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  # Remove development mode to enable standard production build
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "./netlify/plugins/tailwind-fix"

# Don't use redirects here, rely on Next.js routing
# The Next.js plugin handles this automatically 